juju:
  charms:
    wordpress:
      plugins: 
       check_ping 
       check_http 
       check_ssh
       check_disk
    mediawiki:
      plugins:
        check_ping
        check_ssh
    pictor:
      plugins:
        check_ping
        check_http   
  plugins:
     check_ssh:
      desc: SSH Server
     check_ping:
      desc: Server Uptime
     check_http:
      desc: Check http
     check_disk:
      desc: Disk usage
